services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fujitech
      POSTGRES_PASSWORD: fujitech
      POSTGRES_DB: fujitech
    ports:
      - "5432:5432"
    volumes:
      - fujitech_pg:/var/lib/postgresql/data

volumes:
  fujitech_pg:
